### ISSUE TITLE
Purpose of asymmetric_spinLock

### ISSUE THREAD

**Issue by ray-ng** [alibaba/PhotonLibOS#116]
After reading the source code, I can't find the calling of background_try_lock. Every time an AtomicRunQ is initialized, foreground_lock will be called once. Meanwhile, foreground_lock won't conflict with each other. Therefore, asymmetric_spinLock doesn't seem to play a role in Photon thread.

**Comment by lihuiba** [comment]
You are reading carefully, indeed. And you are right, asymmetric_spinLock does not yet play a role at present.

It is actually a step towards work-stealing among the VCPUs in the future. I don't use normal (symmetric) spin lock because I want to minimize overhead to the owner of the RunQ (the running VCPU), in the common case of non-contention.

**Comment by lihuiba** [comment]
> By the way, can we choose to use work-stealing or not in your future design?

Absolutely!

**Comment by beef9999** [comment]
@ray-ng If you have any issues when integrating our project, welcome to contact us. Currently we can provide limited support via wechat

**Comment by ray-ng** [comment]
> @ray-ng If you have any issues when integrating our project, welcome to contact us. Currently we can provide limited support via wechat

Thx so much! How can I get in touch with you or your team?

**Comment by beef9999** [comment]
My email is on my github homepage
