### ISSUE TITLE
协程栈分配优化问题

### ISSUE THREAD

**Issue by ray-ng** [alibaba/PhotonLibOS#117]
在thread_create的时候是否可以优化下，先在当前pthread栈里执行，在insert进waitq的时候再分配协程栈用于保存上下文；这样在竞争少的时候可以明显减少系统调用的开销；或者像bthread那样使用ResourcePool，不过这样无法实现变长栈的需求

**Comment by lihuiba** [comment]
It may lead to degraded performance in common case, if we delay the allocation of stack in thread_create() until insertion into waitq, because that would incur memcpy() to move frames from old stack to new stack. The silent movement of the frames and the objects allocated in them would also incurs compatibility issues.

Photon already has thread pool that may solve your problem.

BTW,, variable-length stack is not on the list yet. I believe large-enough stacks can solve all the problems easily.

**Comment by ray-ng** [comment]
> It may lead to degraded performance in common case, if we delay the allocation of stack in thread_create() until insertion a thread into waitq, because that would incur memcpy() to move frames from old stack to new stack. Furthermore, the silent movement of the frames and the objects allocated in them would also incurs compatibility issues.
> 
> Photon already has thread pool that may solve your problem.
> 
> BTW,, variable-length stack is not on the list yet. I believe large-enough stacks can solve all the problems easily.

Get it. Thank you for your explanation. I will dive into Photon ThreadPool and then figure it out.
