### ISSUE TITLE
Photon Threads Affinity

### ISSUE THREAD

**Issue by aubi1kenobi** [alibaba/PhotonLibOS#138]
Q1. Do you provide a mechanism to set the thread affinity (pin to a cpu core) ? Or is the 'pthread_setaffinity' compatible with Proton threads? (Since ProtonLib crashes every time I use something other than Proton)

**Comment by beef9999** [comment]
vcpu = OS thread
thread = coroutine/fiber

Yes you can use pthread set affinity on a vcpu, more specifically, before photon::init

**Comment by lihuiba** [comment]
> before photon::init

Is this absolutely required?

**Comment by lihuiba** [comment]
> compatible with Proton threads

You can pin a photon vCPU to a physical CPU core with ```pthread_setaffinity```.

**Comment by lihuiba** [comment]
> ProtonLib crashes every time I use something other than Proton

Can you describe more about it? Photon should be OK to interoperate with the outside world. We have some products built with such kind of settings.

**Comment by aubi1kenobi** [comment]
I have about 8 threads. 6 of these threads should all be busy processing data asynchronously.  4 of the threads are 100% 'busy waiting' for socket data, while one thread will be frequently sending socket data.

context switching is detrimental for the above. Even Irqs will be banned on the processing cores.

On the contrary of what you say, Photon isn't playing nice at all with the outside world. 
- I thrown in a simple 'OMP parallel section' (3 lines of code), the app core dumps.
- And Photon threads have the habit of 'running away', never returning. So, I can't run things asynchronously, and I can't add other  thread libs.
Hope this clarifies a bit. If you have a specific question or thing you would like me to clarify just ask.

**Comment by beef9999** [comment]
100% busy loop, that sounds peculiar to me

linux kernel socket is based on interrupt, not polling, no ways to achieve that.

maybe you should try DPDK, which is released in photon 0.6

**Comment by lihuiba** [comment]
> * I thrown in a simple 'OMP parallel section'

You are throwing an exception in a parallel section of OpenMP? If so, the app terminates probably because the exception is not caught by any try { } block. BTW, photon by itself do not throw or catch
any exceptions.


> * Photon threads have the habit of 'running away', never returning

What do you mean by "running away"? I suppose all threads are running "away" 😂, not only photon. And what do you mean by "returning"?  If want to wait for the threads to complete their execution, you can join them.

**Comment by aubi1kenobi** [comment]
@lihuiba 
I have no idea why you assume that an exception was thrown. There was none.
I probably wasn't clear as Im trying to keep it concise.
- OMP code is fine, no exception thrown.
Scenari:
1. Photon alone, no core dumps
2. X-Men alone, no core dumps.    X-Men = {OMP, std::async, ..)
3. Photon + X-Men = core dumps.   

Goal:  Async run doA(), doB(), doC(), doE(),  Concurrent  "Run and forget" ('Run till the end of time') threads. 

Running Away Photon threads:
- doA(), which was launched first, will start running without giving control back so that doB() can start, and  doB() to doC(), etc.
- That is why I added (tried to) other simple threads models to run A,B,C,E async

In a simple use case (main() { doa; dob; doc; doe;} 50-50 chance to get something resembling proper asyc run (yielding is not async).

Bigger goal:
1. Pin doA(), doB(), doC() and doE() to their own separate cpu cores (core 1,2,3,4)
2. Run them async. Not yielding, no context switching, 100% cpu core usage each.

**Comment by beef9999** [comment]
ideas are vague, but code is self-explanatory.

Let me ask this way. Considering we are using C++, can you implement these ideas with std::thread?

If so, please attach the code, we will help to transform it to coroutine, for better performance. Our lib has the same concurrency model and synchronization primitives to std::thread.

If not, let’s continue talking in Slack, rather than posting an bug/issue you are not certain.

**Comment by lihuiba** [comment]
> I have no idea why you assume that an exception was thrown.

Because you mentioned "thrown" 😂. Ok, it's good to know that you didn't thrown anything.



> Goal: Async run doA(), doB(), doC(), doE(), Concurrent "Run and forget" ('Run till the end of time') threads.


> * doA(), which was launched first, will start running without giving control back so that doB() can start, and  doB() to doC(), etc.

Oh, I see. Photon threads do not fit for this scenario. Photon threads are cooperatively scheduled, which **requires** a thread to explicitly yield its control of CPU (either directly or indirectly), so that other threads **on the same vCPU** can get executed.  Common yielding points are sleep(), yield(), and all I/O functions.

I think your doA(), doB(), doC() do not yield, so they do not "give control back" and others can not start.

I suppose that doA(), doB(), doC() do not perform I/O, and they are all CPU-intensive tasks? If so, std::thread should be used, possible initialized as photon's vCPU if needed.

**Comment by aubi1kenobi** [comment]
Hi guys, some of the threads are purely io threads and some are cpu bound. It is a common practice in the low latency world to use 100% of cpu.

1. When running and pinned on a cpu, there is no need to yield (explicit or implicit). And yielding to who/what? one thread per cpu core. 
2. As you know, throughput has different goals than latency. I know your platform is more geared toward throughput, I need you to help me get the best low latency possible out of your platform: yielding, context switching is a big no, unfortunately.
3. I tried stripping away (to minimise overhead)  anything not socket, but my app can't build anymore,
4. On a side note, you keep interchangeably using threads and coroutines. These two paradigms are completely different, and as you clearly said to me,  your coroutines implementation is experimenta. So it is misleading at best when you say you support coroutines.

**Comment by lihuiba** [comment]
@aubi1kenobi 
Photon has been productional for years, and it has a large install base.  And we do have mixed threading of photon + others in some products.

What I tried convey is that, concurrency is difficult, and it becomes more difficult when you try to mix different concurrency models / implementations. You **must** know what you are exactly doing when you do it.



>  I know your platform is more geared toward throughput

Photon is design for performance and efficiency, including both throughput and latency balanced.



>  interchangeably using threads and coroutines

You may want to know that (stackful) coroutine is cooperative thread implemented in user-space. So coroutine is also another form of thread. 



> yielding, context switching is a big no

context switching in photon takes ~10ns, which is far more efficient than kernel threads, and is neglect-able compared to network communication.
