### ISSUE TITLE
Will it support system API hooks in the future? For example, sleep, connect, recv, etc.

### ISSUE THREAD

**Issue by mankouzhuya** [alibaba/PhotonLibOS#465]

**Comment by lihuiba** [comment]
I'm not sure, because none of us have prior experiences on this. And I doubt that its compatibility issues may make it little use in real applications.

Can you describe more about your situation?

**Comment by beef9999** [comment]
@mankouzhuya Because the libc API still has its use. Considering you need to write a file in disk or tmpfs, then libc's write is always the feasible way to do it, even we can also use Photon's capsulation of libaio or io_uring.

In a work, networking is a important part, but not all that we concern. We'd best just provide the alternatives, rather then overwrite them.

Photon's basic networking API calls are in `net/basic_socket.h`. For instance, `photon::net::recv` equals to libc's `recv`, and can only work in the coroutine runtime.
