### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by silviucpp** [alibaba/PhotonLibOS#75]
Can you add into the network benchmark also https://github.com/Qihoo360/evpp ?
It's way better than many other libraries used to compare with Photon

**Comment by beef9999** [comment]
Because I didn't know how to specify buffer size in evpp's tcp server example, so I only run its [ping-pong server](https://github.com/Qihoo360/evpp/blob/master/examples/pingpong/server.cc) tests in my own environment. (The streaming test would require a fixed buffer size)

The results showed that it ranked the 3rd, a little bit slower than asio. Not sure why they claimed that they are faster than asio.

**Comment by beef9999** [comment]
I'll add its benchmark into our list

**Comment by silviucpp** [comment]
Do you have the benchmark code in the repo ? I cannot see it. I want to see how you compiled evpp . 

Silviu

**Comment by beef9999** [comment]
The Photon’s bench code is in the example/net-perf .   The instructions are just in the front page.

I compiled evpp simply by cmake .. and make -j
