### ISSUE TITLE
compare with async_simple?

### ISSUE THREAD

**Issue by wanghenshui** [alibaba/PhotonLibOS#81]
https://github.com/alibaba/async_simple

natice stackless coroutine and it's also a alibaba's project

**Comment by beef9999** [comment]
Yes we are definitely aware of this project. According to our previous investigation, `async_simple` doesn't have a IO scheduler. And in the example, it has to bind with `boost::asio` in order to use the IO scheduler.
According to our tests, its performance cannot surpass asio. So of course, not faster than photon.

**Comment by beef9999** [comment]
`async_simple` is a wrapper for C++20 coroutine syntax.

**Comment by wanghenshui** [comment]
> According to our tests, the performance of the example cannot surpass asio. So of course, not faster than photon.

OK
