### ISSUE TITLE
Suggestion: Uniform code style

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/PhotonLibOS#99]
用clang-format格式化一下？

**Comment by lihuiba** [comment]
我们有些同学在部分代码当中尝试过clang-format，整体感觉结果有点丑陋，就没有推广。另外我们也愿意给不同的维护者*一点点*自由空间，可以在*一定程度*上定义自己维护的文件的风格，而不是简单机械地应用一个风格。

Some of us have tried clang-format in some cpp files, but the results overall looked a bit ugly, so we didn't make it a standard. And for another thing, we'd like to give every maintainer *a bit of* freedom to use, *to some degree*, his/her own coding style, instead of conforming rigidly to a single one.

**Comment by 4kangjc** [comment]
I see.

**Comment by lihuiba** [comment]
当然，修改已有文件的时候，要遵从该文件自己的风格。

Of course, when modifying an existing file, one should conform to its existing style.

**Comment by 4kangjc** [comment]
But there are different code styles in one file
